### ISSUE TITLE
Display Cluster status icon in left nav

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#32]
Display a cluster status icon next to each cluster in the left nav (as well as on the Cluster detail view, and potentially next to the cluster name in the crumb trails).

To determine the Cluster status, poll the following API points at regular intervals (every 10 seconds). (Refreshing the Cluster detail view should also do a poll at that time, as well).
1. Do a Riak Ping (`explorer.getRiakPing()`) for each node in the cluster.
2. (Optional) Check `/control/clusters/default/status`, make sure the status of each node is `valid`. (Note: the cluster status is only concerned with the `riak-admin cluster plan` type of operations, whether nodes are joining or leaving. It does not reflect when a node is stopped or unreachable.) Sample status API response:
   
   ``` json
   {"status":{
   "nodes":[
     {"id":"riak@127.0.0.1","status":"valid","ring_percentage":100.0,
         "pending_percentage":null}], 
   "valid":1,"leaving":0,"exiting":0,"joining":0,"down":0},
   "links":{"self":"/control/clusters/default/status"}}
   ```

The Cluster status should be determined as follows (feel free to use appropriate icons to denote):
- Cluster status: **OK**/valid when all nodes in the cluster are ok.
- Cluster status: **Warning**/problems when at least one (but not all) nodes are invalid or unreachable.
- Cluster status: **Down** when all the nodes in the cluster are unreachable.

There's another possibility, that of Explorer returning an HTTP 500 error (for example, when the 'designated contact' node for a cluster is unreachable). We should either mark all clusters as Down in that case, or have a separate 'Explorer is broken' status icon.

(Note: This should be implemented after Issue #31, after creating a proper Node model (instead of using an anonymous JSON object for nodes, as currently done).)

_API-side change:_ It would be helpful to move the Riak Pings of all the nodes API-side, so that a call to `/explore/clusters/$cluster/nodes` also returned 'up/down' status for each node. That way, there would be only one API resource to poll for a cluster, instead of X (one for each node).

**Comment by paultannenbaum** [comment]
Screen shot (internet is flaky so linking to DropBox):
https://www.dropbox.com/s/6owe4nhlfv8xece/Screenshot%202016-01-09%2016.58.17.png?dl=0

**Comment by dmitrizagidulin** [comment]
@paultannenbaum - you can upload the image directly into the issue comment. (the 'selecting them' link right below the textbox)
