### ISSUE TITLE
Implement Browse Logs view off of Node details view

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#36]
Now that https://github.com/basho-labs/riak_explorer/issues/98 is implemented, create a route/template to browse (and download) the Riak log files (see the Explorer issue, above for the list of which logs) for a given node.

See http://basho-labs.github.io/riak_explorer/docs/api.html#node-log-files-collection-get for API docs.

**Comment by paultannenbaum** [comment]
Screenshot:
<img width="1440" alt="screenshot 2016-01-06 11 33 06" src="https://cloud.githubusercontent.com/assets/220885/12152420/6d0fb6cc-b469-11e5-9612-e7621bf7df11.png">
