### ISSUE TITLE
Implement Browse Riak Config Files view off of Node details

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#37]
Now that https://github.com/basho-labs/riak_explorer/issues/99 is implemented, create an Ember route/template/etc to:
- list the available Riak config files for a given node
- view/download a specific config file.

Note: This is somewhat related, but different from https://github.com/basho-labs/riak_explorer/issues/95 "Implement 'riak config effective' API endpoint per node" -- effective configs is the combination of all the config settings as interpreted by Riak (plus many default settings not actually in the config files).
Whereas this issue is to display the actual `riak.conf` etc files, for aid with troubleshooting.

See http://basho-labs.github.io/riak_explorer/docs/api.html#node-config-files-collection-get for API docs.

**Comment by dmitrizagidulin** [comment]
The API is now implemented, as of https://github.com/basho-labs/riak_explorer/pull/105

**Comment by paultannenbaum** [comment]
Screenshot:
<img width="1440" alt="screenshot 2016-01-07 20 00 29" src="https://cloud.githubusercontent.com/assets/220885/12190094/5bef96a8-b579-11e5-99ad-397689c3dfdb.png">

**Comment by dmitrizagidulin** [comment]
This looks awesome, btw.

**Comment by paultannenbaum** [comment]
Thanks @dmitrizagidulin! Feel free to provide any feedback if you feel so inclined ;) Always appreciate your insight
