### ISSUE TITLE
Implement a 'Reload object' button

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#42]
Implement a 'Reload' button that would re-fetch a Riak object from the cluster on all the Object detail routes (plain object, edit object, Set, Counter, Map).

**Comment by paultannenbaum** [comment]
Going ahead and implementing this, but I do have a question. How is the UI ever showing a stale state of that object once we are in the object detail view? Is it because it could have been changed somewhere other than explorer since the object list was cached?

**Comment by dmitrizagidulin** [comment]
Yeah, exactly. It's for when another actor (another Explorer gui, or, more likely, a piece of code that a developer is testing) has changed the object after it was loaded into object detail view.
