### ISSUE TITLE
Display cluster type (Open Source or Enterprise Edition)

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#45]
With https://github.com/basho-labs/riak_explorer/pull/102, we now have the ability to tell whether a cluster is Open Source (`oss`) or Enterprise Edition (`ee`) Riak:

``` json
{
    "clusters": [
        {
            "development_mode": false,
            "id": "production1",
            "riak_node": "riak@127.0.0.1",
            "riak_type": "oss"
        },
...
}
```

Add a Cluster properties section to the Cluster overview page, that displays the following:
- Whether the cluster is in development mode
- Riak cluster type (ee / oss / unavailable)

**Comment by paultannenbaum** [comment]
My master branch for the `riak_explorer` project is current, and I restarted both my running nodes and the application itself, but I am still not seeing the `riak_type` property coming through. Do I have to run any kind of update task/migration to get the updated server response?

**Comment by dmitrizagidulin** [comment]
After refreshing the riak_explorer repo, you'll want to:
1. stop the explorer app
2. run `make recompile`.
3. start it back up.

If that doesn't work, you may need to do 'make stage' again. (Though that resets your riak_explorer.conf file -- you'll need to either back up & restore it, or just re-set-up the clusters again).
