### ISSUE TITLE
Provide help / additional info in Bucket and Bucket Type Properties views

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#66]
1. Provide explanations / defaults in the Bucket and Bucket Type Props sections. Use `bucket_props.json` from [riak-help-json](https://github.com/basho-labs/riak-help-json#bucket-properties-help) for the descriptions / additional info.
2. Display the default values, wherever applicable, possibly in a column next to the current. Or in parentheses next to the current. Sort of like: `r: 1 (default: 2)`, that sort of thing.
3. When a bucket property value is different from default, highlight it in some fashion (turn that line bold, for example).

**Comment by paultannenbaum** [comment]
<img width="1439" alt="screenshot 2016-02-10 14 44 30" src="https://cloud.githubusercontent.com/assets/220885/12964584/c1f2779e-d005-11e5-9970-80cd4f9a9342.png">
