### ISSUE TITLE
Implement a Help page

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#75]
Implement a Help page (route/template etc) that links to various Explorer and Riak related resources:
- Display instructions on how to set up a cluster in `riak_explorer.conf`
- Link to the Explorer repo (and README). 
- Link to the Explorer API docs
- Link to the Riak mailing list and IRC channel
- Link to Basho online Docs
- For Enterprise users, link to Zendesk, and to the Enterprise Riak download page.

In addition, remove the Resources / API Docs link in the Explorer sidebar. Instead, have a Help link (with the current Resources icon) in the top right section of the top nav bar. (And remove the other two placeholder links there).

**Comment by dmitrizagidulin** [comment]
The help page looks great! :)

**Comment by paultannenbaum** [comment]
Thanks @dmitrizagidulin!
